module Rippler
  Contacts = Hash[ *%W[
    OpenCoin            rJR7gjNe3DpJ7kpB4CHBxjDKfwVMpTKPpj
    OpenCoin-1          r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV
    ADDRESS_ONE         rrrrrrrrrrrrrrrrrrrrBZbvji

    bitstamp            rvYAfWj5gh67oV6fW32ZzP3Aw4Eubs59B
    bitstamp_hotwallet  rrpNnNLKrartuEqfJGpqyDwPj1AFPg9vn1
    weex_btc            rpvfJ4mR6QQAeogpXEKnuyGBx8mYCSnYZi
    weex_aud            rBcYpuDT1aXNo4jnqczWJTytKGdBGufsre
    weex_cad            r47RkFi1Ew3LvCNKT6ufw3ZCyj5AJiLHi9
    weex_usd            r9vbV3EHvXWjSkeQ6CAcYVPGeq7TuiXY2X

    X.Veirou            rhq5LEZSWHWY6H3raiC2KGe8TVeirou4BS
    X.Wow               rHD7Bs8Zk1oQeUhLjPrsFStFcRE2NWoWpe
    X.Reya              rEyAJhMMi5WNzgdkY67vN7ivfiQnh3itXY
    X.Founder.1         rfbKLd1VLB3o6fpkhCJexckArjoMmBm2wG
    X.9billions         rstKSeB2Qx7zrwSkyc7X9Xm5nYTJqtL3iM
    X.77millions        rB5TihdPbKgMrkFqrqUC3yLdE8hhv4BdeY
    X.10millions        rHrSTVSjMsZKeZMenkpeLgHGvY5svPkRvR
    X.001               rKdtD8YQXCJAnXoXQfmn645FybiaFWVghs
    X.002               ramJoEsBUHc299vFuMvn8NgLrF3Qrt3XV4

    TTBit               rGwUWgN5BEg3QGNY3RX2HfYowjUTZdid3E
    BankOfZed           ra88Lr8fyo9cUTuyjVFMTrvTSBU93erjyh
    AlanFromZed         rhR5j5LXsujSuwG2bcn1P39utdTA79ceaW
    BobFromZed          r4ixnhDRE5VktpgtFkw5L8v1bNGsFusQJS
    ChrisFromZed        rPA9PquwamoriknybdishCdWp6N1m2iEF8
    SecondBankOfZed     rnqQ7YEStMBBqn6qBP4AYsyGhy1RKfUeRR

    molecular           rpH3zuMch2GrrYX724xGWwbMGwiQ5RbSAU
    Ente                rNEtVs4kNeESF5HbWCDZMYcWwKZ5iKwUEr
    herzmeister         rUdPvX9YN1NwyniwiJeSW6y3YKZL84gsB6
    ribuck              ra3a5cfr83b5FTh1YDURqWQh8HTbHEwdyD
    Spekulatius         rNHf9nnX4JgHferxjRxmapDev7mWQZ6XXd
    Bitobsessed         rKfd86S25PUdVquk41xedH5jNX4bZ8DiA7
    Akka                r9RpJFpD6vkKhgHhrRjkgofSbNsE1oYFZ1
    bbit                rB7qiwEDrcMShUN3Jd8LwXr4RJ7RWBaQu8
    ryanAC              rJA6mGHsw5yCynLFRe3rjGqaCMk2YpmuMy
    phelix              rM3puGNYNQTWuqsQpkzxSpmWFqGGuY29Vb
    kokojie             rNexqWdz7q16e6PPBDsD2XxxzFS64SAEYS
    PeterLambert        rGsLivkDjTZHFQ8oV2h81uTcbTpgjEaEY7
    jorgen              rQay7bQ3XoZcT6E3c8uDopZdnWaMBxWea2
    Belkaar             rJVshcxcxSAXkgzg1PiUQWr5TodTNAETva
    grondilu            rpuebQXsR7kAst5yidD6fmGmJHD4niXzbo
    TimoY               rG8VFQPaJB2gNjx29Et1wKUJettQP1eLmk
    Melbustus           rKAw7uHrdUUEqtfFhBBHe6unyh57PLpCc4
    Aahzman             r9TWUUN8duW1rDqJ2yz2wjksc8A9BpxPUh
    AlexNeto            rp3Papsq3aXf3gswfgfaqgegjLAEVaw8V1
    thoughtcourier      rn7iD6DpnCwH8kjJDCsENibMXkgmJkRCRz
    znort987            rnozMbmRYfqvn15iBFNeeRJs95gagR2B46
    RaTTuS              rw65MQQDpWQYGxFEtcQk3r6dpeZ2gx5zff
    romerun             rU3cgYfpu9jedq8GnW43ArEntsWTD6Sg4n
    PRab                rEdaspCuZQWrxrGiGMQW3iPXjmEnfUxkqN
    duckbillp           rsa8BE2DfzLC52XQMUv3gECoZXQL7FNGig
    Mageant             rPDT5apJsfy8Jbz3M8jXzXskMsKAANhM9p
    Severian            rDqSvk6fRhKq5tSW7GpWFFHG5pG2XE3mtR
    lebing              rJFGHvCtpPrftTmeNAs8bYy5xUeTaxCD5t
    gweedo              rKFX2Gvk4jLtgEGMC2qDmMi18Zw4bewrjK
    OgNasty             r3hRKGL1JKWXJDujchZXrs6Pa16xsM6JjS
    Mogly               r9uVRhJEKsJVaxsU3c3rimzLWKYRmDUcX2
    Warry               rLgbpjNtVQ6ENjn5nGgnyi26gn9EBjuKhj
    supert              rh7eAu9SrFsE2fVfc1PJTs1WYDHGAUde6V
    Evan                rfpS692WVbsSXyv6R48K8A2LHCqdvYaS2w
    BBQKorv             rrhAmxxwxEchP2iJdGh7nrwwAK4u3BzaLC
    Mjbmonetarymetals   rNTXjBWitdKUxr6o1zyi4FsjQ8UeP3JCKd
    khal                rpUjkUUcbteWbXrPt4aXAMwzotSPzQJHQt
    Trading             rNPHozULzm5nKavgXxbq8tcwAcxyhZpTBw
    Schleicher          rGGxDC8VZ7zHmVKt6XK6sc7fUziNtvohWC
    ripper234           rhQ7mQ1JJKygoxh7SoCaKNZB4GufdCRiH3
    alexkravets         rKQLJpoBagwGiE7LVcY8YfDfE6EUREJjeq
    comboy              rLHMoLsuLhg1Q741bHNjv7jhMqr6karoG7
    djbaniel            rNnLFDCRrAtuESodmwamAasMBZqCmkqQH9
    wyodude             rwJBiKfYKRFX59GykztmGdedUvmV64LpaK
    misterbigg          rwLYfeQHfucz8wD6tFPY9Ms6ovmMBCCpMd
    endlesscustoms      rN6DeCG5VvmfqjBywwoE24oXQsHzRDUfzh
    avegetable          r9MZGmnGc1qo64ZQbxijVFCdcNt741nkYE
    runlinux            rsAMwJ4BjuEwb5dkd84XW9WM5KvauxcGAU
    nomnomnom           rp3qwd4zb8Ywq8rFrxLgijvyYKMa68FbxW
    nealmcb             r3NQyByq6KfvnD1PXu3jwGzdsVGn1HEJNq
    TTBit               rGwUWgN5BEg3QGNY3RX2HfYowjUTZdid3E
    plummonkey          r3PDtZSa5LiYp1Ysn1vMuMzB59RzV3W9QH
    magnebit            rQrUJLNcjnaZJjqMjaiPHxGa7eipzyf7b
    mpfrank             rnfLDQaxN7isxzWZuc6BM8jeiCb2WSGpdG
    Bitcoining          raW4tvsndX8fkunTqpHWsT8L5BErB5KEJd
    Pteppic             rwBYyfufTzk77zUSKEu4MvixfarC35av1J
    Lohoris             rDBfeSsYGwDiXWdTARYHsxUtvzAXgARFMu
    MatthewNWright      rwTbS9jC9a1Yu57j7ZUwEY5oQTo86o6VXR
    wormbog             rLveNTH6EA3tY4BzpdvgkukJ3oTxWk2UHM
    GoWest              rszHYGgWBTCwCUQCUjCPwmx6zLinbqXZvT
    VitalikButerin      rJ2gXg1xcYW6756fBj393Dd9ZekJP45odZ
    ElectricMucus       rpJwZ8dcJLVydewhhfQEgMCQxFyMorH9rG
    RRTaylor-Almanza    rE4StrJNLHahqBjpVdz5pj2Zgqtvk1fwuu
    hazek               rsQP8f9fLtd58hwjEArJz2evtrKULnCNif
    FlipPro             rNSnpURu2o7mD9JPjaLsdUw2HEMx5xHzd
    JoelKatz            rHzWtXTBrArrGoLDixQAgcSD2dBisM19fF
    evoorhees           rpfxDFsjDNtzSBCALKuWoWMkpRp4vxvgrG
    SunnyKing           rKMSa2tRir1kcKW6qrfRBc2fRZLCzVsxxX
    dacoinminster       rKj9ngzutnjmuiSJTTkUm3NBBt83v2uc4r
    jimbobway           rEMqTpu21XNk62QjTgVXKDig5HUpNnHvij
    nanotube            rBJwwXADHqbwsp6yhrqoyt2nmFx9FB83Th
    snapsunny           rNuFYAu1aUYbATH3qCs27BjPc5dDHVgY1z
    tbcoin              rsvAk3NoSSZwCTv9epzrKtFkAkHLVwEBmw
    Bimmerhead          rJzAwqVF3fuKvxRegZMfrFSQQrXJA9Dpms
    MonsterTent         r3vaUaLbUgJdg61wuSiX4byD9ofkbPnKVa
    rta                 rBxi9xHEmvSJHAxrJ21sQNprs9xuENgs1Z
    fimp                rGnSAso57ca5hBtSYuXzT5rjCEFQ1RWAec
    intel-core-i7       rsmbvYkXWQ9LH3JHoHPg9rmYhQGi5M7ue4
    btc24               r96WyAeNMykJKpdMi54V5WCqQEqfqhs6oA
    jl2012              rnKhmoH1BFrh7CfDnJ21XW6arPySDXUPFZ
    Prattler            rnmB7GYEB9Xz2qBmiU8L6qdpCzd9FdvvJQ
    commonancestor      rGguLh5qc15WLntiB7zPfE2XCBdB7HZLdi
    sneef               rGQCcCAG2fFmPY7X9zDZEhCnMp5JgAeziS
    zulzedd             rJYHWjtcZaHfDTL7P8Dh5zkk1JdZsxiYef
    Snowfire            rpVbjBotUFCoi9xPu3BqYXZhTLpgZbQpoZ
    Otoh                rKWYoFVMsKjZZhCZMFSagYmasqGZFYkpYu
    Deafboy             rUAScykwHVqU2d4rb4twHbpDa7C81p4MSA
    speeder             rNzJ6ikJKXAxAaTPMZCcXr2sFkmg9a2GM9
    nelisky             rLDDq8ZGhCaVBP8MyYTifhCJzgWPQBjwpt
    mrmx                rKishCqMiQG6zhFHPjrFhXztLDjZteNmGP
    drewdtom            rsZvcvACPWoTN2Eazzb5radzQX18s3DuK8
    MadSweeney          r4pqusLQxgFNQQNByJMcTvQcYG9v1GpBum
    Digigami            rHCSeQNZZz7FWbxvLjB2RzF1CrBeUcDj7J
    jking               rMpB2AsrDTdbynCB48hg8MwHLD4wtXJfRJ
    justusranvier       rnZoz4R1o6GupernFX6bey34uj4g45scLZ
    sron                rNgfXZpCHQm4wT2CBoGpJeTnuEm1zKqD4x
    Krax                razxPYEPwt8JkH5RUkoTakMLEA9PJMuokT
    PEDTrader           r4nj4U8kwYZgXCUSQehPBW2QqbPPvcyGEV
    thebankofbitcoins   rKdxsLnSodtD4BJwxPM1WssTGLXBNK7oxb


    arvicco             rnZoUopPFXRSVGdeDkgbqdft8SbXfJxKYh
    paysafecardbitcoin  rN4kvobWCZVSzgLmo27B4kMjakAL31pMSr
    Lethn               r4DpNXFTohg1hgBKxrYv8YBtahKNAALjeH
    nikkus              rUhcZuPQBrykExj1VSfLnaeLdu2hJmVe9e
    filharvey           rJRFxWe3KxmhMfW7am5hFE9pkciAJHefeD
    ablewasiereisawelba rPtTbUkhLZ9e2a7H3TCHcHmSa35jTnQHoa
    luffy               r3mjrPe1S4vHe2g6CTCeb6ezcPfpDywQAs
    thepwnorbpwnd       rLQ1WWeCVuM523iMRC9PCLpyFU8YkWqDdR
    lightlord           raAw68E3T6Eh4h5Qfb1ZxsWzyHkY8BZJRN
    Wolf0               rwcpov2ZZmPpo6sjeg4n2oZx94uAYBQ21o
    thepickingpair      rht576qwyKXZ26JEGHYpC3N3atjNS8oM5j
    Luceo               rGZL3cCV6Er5Tiag9tStGhseF4NDBxbxQr
    Luceo-1             rJpuugf8o4NfvorsTGwGyyy11Hi3j9514H
    21after2            rwuoJnBP4kyfR6Bry8ruLNyxubuk37w6gi
    t.o.m.              r4b5wQJL9qfqGZA6WQksE9spuYi4fmgDde
    octopus             r33dwR8VbfDvHptF2AYzp9JHjR7iVetqM
    MichaelBliss        rB2VLRRZejCMpDCyvGNn4nEHRLycwY7H8z
    nckfor              rD2yesqWXxgEztU6khSjts7tx8CF6VN3k3
    FirewallXIII        rEvYxDNoz8aFSRRWH6JoKBhBAqx6xDMN3G
    00null              rhr3wb58NyicoBBXGfPQtctXxk1X8ZhwcM
    Isamaru             rGsfVSM9etepbYoa52AScPRd2eSdv86ZDf
    ragmondo            rHm9QPX7v2xz9JMozrYnJynfgEhnQ6Aaeo
    trippp              rL4px896Gf2r5PDru38jsJt3qTN9NmpgEd
    TheRenix            rMPJ77FoY86cLLzhQ3ETnvNdAvy6A4UMqR
    simonk83            r3U8PomU1pw4T48cmXVahUNuUerNVcbwto
    rme                 rJeuPjq9XBZkuxk51hmXSsFmANy7JbBCRC
    Ecks                rJaBUL6npe6yvoJU7e5nuRgAaMoa3njnQ8
    NABiT               rLorFPMtVzutmcZBDGpAeQLfVyCL19p1qK
    JesterOfTortuga     rDGLPeQTbd7ntNRNdwAtgAjnUPf7YwDHGz
    ryanbrownstar       rvTZGvDaKza8Zuhm4E7vnLtTuMU2MgwX3
    mmkiwi              rJpG5GJrpKBabbqGphfijjdZe2bkyPewL7
    camolist            rBzu6o32DoHtHUvRYUKwcHMsgz1BTSTyek
    cambda              rfxAqtZA9Knb8mb1Gij4Y6rFfTfp6FWSTZ
    cambda-1            rBBSghHNdpbBuT5kiGruX5TjofWLF2fi74
    TheInventor         r7a3uqQREUU6tEYnsCTFWh31DeVHWNp2G
    rizzla              rLnhMYFwqUkc2D8ojJmhQkNuytaBsyzVG3
    Moshi               r9fupyMm63XMvbAozvzjLyHdJHCtLEKveE
    bachus              rKQLwGTe6NX16iSEuS88bi3FEqZnbwF7EB
    helloworld          rwDo98FnbCp3qUN5CkwDcK4rFfbyW3Kzqq
    Cyberdyne           ragN8YEhHjXbgeGrNGLw9wuxQeq1d8qHk
    cardinalG           rQr973QcHXx1NCfXpQdLPpnGmMrkDjwRXB
    dalek               r3HpcvyJUhpGzJGa7KBZcvo35EiDqLtU1V
    Slackware1995       rLHacQyTzfRjHMp7yFzXu18cbt6KteSXBP
    WalterRothbard      rwaaH5CCdWe8V7kBbXQonpFyKbRDePF9Vc
    spndr7              rUusFTWNUDYqKnAg4tiZLTAyRdUMaVFVUG
    kakobrekla          rHrkFodY9f3DxQnSsHiu6R1j4JvTYfFnRS
    ny2cafuse           rBh3KyjpANw5GXbt9AmCiFB2MbYGxWSCWa
    chris200x9          r9MmCAquMciDwGRqKUXvayK2LAayPSvYuz
    Prospero            rB8N1ohjVKtMiZVivSY3H6Y3ABcAMJce36
    Atruk               rp3uz9jcb8LkMpMvwsfFTaCpkEgAGxNnKj
    Isokivi             rUjVzMqFpFYLQ8PoKb46psWuKhkxgZFTnx
    Anormalname         rp9DmXB6uxkooTeGpdtjaj8eT8V3ENaads
    Luno                rDcW2mqMKGHZ4iFKkTSyHyBT4AtLNBwge
    weex@bitcointalk    rEjC6w3m7ENkmD9SAyFyfKgRgeNz7HbkbW
    gbl08ma             rsgg1U8UpYodp1GM3NDaYfMrZge97Gpvc9
    tosku               rBs43YZMn5QsYY9jZYcG4C3egEebUfGWh3
    BitcoinG            r3CxMDQFX1Atq1vQN5sqVsjm3rawGSwd32
    Gzarcov             rEg8hTqY7jhSkeFirfE5Fm7BF72WaaCnrB
    milly6              rQaxmmRMasgt1edq8pfJKCfbkEiSp5FqXJ
    crazyearner         rBcrMMTUKAQJd5tMEsy1zyTGRiy79gY9K3
    elelegzet           rBKnNboJeGxTwQM1agrXp28WcVWKtPPQah
    Myrddindc           rp2ewp8uH4zi35T2oWkfpETT3rQ4qBBZzt
    Ivica               ra6FCgRD4Ye4PNcTRhmiXaSzpJKo1PQEzh
    DrG                 rQrnuAtfePuz2fsSDTakuDZn594fi9x7dP
    DrG-1               rJEZjBv27ZHCPAoDtTBJb9r82VnUdkRd77
    UnitClick           rLKojeESeKi9mdBuPLkiQhCxs4wh8iKy2W
    saddambitcoin       rMSEYpzcRtkiA5kkxYEWZtvLr8u3jnn385
    helloworld111       rwGAnUvzT5yrDz6dXxm6MWVhpV9abm39W3
    dykast              rQfwn3GVHVEfTpjqU2Y3BoMGAGHrw43XnT
    BurbolGii           rDYwnqGbUazEuMfebQwLprCQQXWbYgXTMa
    BC12345             rNy61KXKUYPMFf5fMV6ojo3u98dc5WhiVu
    Eegnylot  rPKwrbDS6GC61QF1NuyTCohK926ns2vEG3
  ]]

  Addresses = Contacts.invert
end
